### ISSUE TITLE
Error when compiling on WSL

### ISSUE THREAD

**Issue by wolicodes** [TheEssenceOfDarkness/darksplit#11]
Hello, here's the error: 

```
LINK chronos
/usr/bin/ld: error: LLVM gold plugin has failed to create LTO module: Unknown attribute kind (70) (Producer: 'LLVM13.0.0-rust-1.57.0-stable' Reader: 'LLVM 10.0.0')
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:35: chronos] Error 1
```

**Comment by DarkRTA** [comment]
This sounds more like an issue with your build environment.
Can you give me information about what distro you are using under WSL.

**Comment by wolicodes** [comment]
It's Ubuntu, here are the versions of the different software:

```
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu

rustc 1.57.0

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by DarkRTA** [comment]
Alright so I'm thinking `-flto` with `clang` is causing problems for your specific build environment. You should edit the first line of the `Makefile` and remove that flag, and optionally switch to using `gcc` instead of `clang`.

**Comment by wolicodes** [comment]
It was indeed the `-flto` option, works now even when compiling with `clang`.
Thanks :)
