### ISSUE TITLE
Global hotkeys works only with NumLock off

### ISSUE THREAD

**Issue by tepiloxtl** [TheEssenceOfDarkness/darksplit#18]
I have rebound my start/stop and reset hotkeys to F13 and F14 respectively to use with a keypad, but even when bound to a normal keyboard button like A, it seems that any global hotkey only fires when Num Lock is disabled

**Comment by DarkRTA** [comment]
If you are talking about the global hotkeys here, they are handled by livesplit-core and not by chronos.

I could try updating that but afaik the hotkey code hasn't been touched in a while.

**Comment by DarkRTA** [comment]
I updated livesplit-core in the latest commit if you want to try it anyway. Information about your OS would also be helpful here.

**Comment by DarkRTA** [comment]
Oh I just realized what is going on here. Certain keys report different values depending on if Num Lock is enabled or not. This is not something I can fix and this would have to be worked around in `livesplit-core`.

Closing as this is not a problem with chronos specifically.
